pyt/__main__.py
This seems to fix https://github.com/python-security/pyt/issues/42 although when it's on PyPI maybe we'll change it to just `pyt` instead of `python -m pyt`.
=> [ui] fixed prog name from __main__.py to python -m pyt

pyt/__main__.py, pyt/vulnerabilities.py, pyt/vulnerability_log.py
This is an attempt to fix https://github.com/python-security/pyt/issues/46. Let me know what you think @Thalmann.
=> [UI] added trim option

.gitignore, example/example_inputs/django_views.py, example/example_inputs/flask_function_and_normal_functions.py, example/vulnerable_code/django_XSS.py, pyt/__main__.py, pyt/framework_adaptor.py, pyt/framework_helper.py, pyt/trigger_definitions/django_trigger_words.pyt, pyt/vulnerabilities.py, tests/framework_helper_test.py, tests/vulnerabilities_test.py
This adds a framework adaptor for Django (#71) and some other Django-friendly changes.
=> Add Django framework adaptor

pyt/draw.py
Just replaced subprocess.run with a backward compatible function subprocess.call
=> pyt/draw.py: Version compatible upto 3.3.7

pyt/vulnerabilities.py
Was looking at https://github.com/python-security/pyt/pull/81 and wanted to cleanup a bit before I continued.
Removed unnecessary code from the get_vulnerability function & made secondary_nodes a default empty list.
=> [cleanup] vulnerabilities.py

setup.py
This should fix https://github.com/python-security/pyt/issues/104 and bump the version to 0.30, and fix the `package_data` issue @MacBox7 found in the https://github.com/python-security/pyt/pull/103 discussion.
Thanks @MacBox7 :D I will push the tags, can I be an owner of the PyPI package i.e. `Manage` rights so that I can update it myself too?
=> [setup.py] Unpin reqs, include package_data, bump to 0.30

pyt/__main__.py, pyt/baseline.py, pyt/formatters/json.py, tests/command_line_test.py
[Issue 101](https://github.com/python-security/pyt/issues/101)
I coded "baseline support" script but i couldnt implement it. i am taking this error: "ValueError: I/O operation on closed file."
#python3 -m  pyt -f app.py  --baseline test.json
**Output**: 
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/gunal/pyt/pyt/__main__.py", line 370, in <module>
main()
File "/home/gunal/pyt/pyt/__main__.py", line 316, in main
compare(json.report(vulnerabilities, sys.stdout),baseline)
File "/home/gunal/pyt/pyt/formatters/json.py", line 31, in report
with fileobj:
ValueError: I/O operation on closed file.
=> Baseline support 

pyt/argument_helpers.py, pyt/vulnerability_definitions/all_trigger_words.pyt
This just makes the default settings easier for new users
=> Combine flask and django trigger words, make it the default

tests/cfg_test.py
Created  `try_orelse_with_no_variables_to_save.py` and `try_orelse_with_no_variables_to_save_and_no_args.py` for issue #62
=> Created new tests for cfg_test.py

pyt/helper_visitors/vars_visitor.py, tests/helper_visitors/vars_visitor_test.py
This patch set adds unit tests and increases coverage for `vars_visitor.py`.
This also patch set also fix a slight typo in `vars_visitor.py`.
Partially-Closes: #134
Signed-off-by: Tin Lam <tin@irrational.io>
=> Add unit test cases

pyt/helper_visitors/vars_visitor.py, tests/helper_visitors/vars_visitor_test.py
of the type `{'a': 1, **x}`. The `**x` will have key `None`.
Before it would crash.
=> Vars visitor handles python 3.5 dict syntax

pyt/core/ast_helper.py, tests/cfg/import_test.py
Code where we call a method of something which isn't a variable name
e.g.
```py
yesterday = (date.today() - timedelta(days=1)).strftime("%Y-%m-%d")
```
was causing pyt to crash.
Previously the else branch would only handle ast.Attribute, and crash on
everything else.
```
Traceback (most recent call last):
File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/pyt/pyt/__main__.py", line 141, in <module>
main()
File "/pyt/pyt/__main__.py", line 97, in main
path
File "/pyt/pyt/cfg/make_cfg.py", line 40, in make_cfg
module_definitions
File "/pyt/pyt/cfg/expr_visitor.py", line 60, in __init__
self.init_cfg(node)
File "/pyt/pyt/cfg/expr_visitor.py", line 67, in init_cfg …
```
=> Make get_call_names more resilient

examples/vulnerable_code/sql/sqli.py, pyt/cfg/stmt_visitor.py, pyt/core/node_types.py, pyt/helper_visitors/__init__.py, pyt/helper_visitors/call_visitor.py, pyt/helper_visitors/right_hand_side_visitor.py, pyt/vulnerabilities/trigger_definitions_parser.py, pyt/vulnerabilities/vulnerabilities.py, pyt/vulnerabilities/vulnerability_helper.py, pyt/vulnerability_definitions/all_trigger_words.pyt, pyt/vulnerability_definitions/django_trigger_words.pyt, pyt/vulnerability_definitions/flask_trigger_words.pyt, pyt/vulnerability_definitions/test_positions.pyt, pyt/vulnerability_definitions/test_triggers.pyt, tests/base_test_case.py, tests/helper_visitors/call_visitor_test.py, tests/vulnerabilities/vulnerabilities_across_files_test.py, tests/vulnerabilities/vulnerabilities_base_test_case.py, tests/vulnerabilities/vulnerabilities_test.py
The aim of this is to reduce the number of false positives.
In the json trigger file you can specify a list of arg positions or
keywords which propagate or ignore taint.
So e.g there may be an execute function
where the first argument is raw SQL query text which is affected by
taint, but any other arguments are variables passed in to the prepared SQL
statement and (we assume) can be tainted user input without a problem.
To do this we can no longer just use the RHSVisitor to see which
variables are used by a sink. We need the results of each arg / kwarg
separately.
There is the added complication of *args and **kwargs where we need to
determine if a RHS variable could pass into a propagating arg / kwarg or not.
Probably the best way to understand it is to look at the added test cases.
#145
=> Certain args, kwargs of sink functions are affected by taint

pyt/core/ast_helper.py
The dependency graph of a large Python app can be quite a mess.
Previously, we were regenerating the AST of files many times, as they were
imported by different modules.
Adding a simple LRU cache [path -> AST tree] sped up pyt on one of my
code bases by 5x.
We currently only mutate newly created artificial nodes, so we can store
one copy of each module's AST and expect it to be static.
We can make it even faster by setting `maxsize=None`, so there is no eviction
logic, but for now I think it's already an improvement.
An alternative could be to rewrite the code which deals with imports.
=> Cache of AST tree by module path

.coveragerc, pyt/__main__.py, pyt/cfg/expr_visitor.py, pyt/cfg/make_cfg.py, pyt/cfg/stmt_visitor.py, pyt/core/project_handler.py, pyt/usage.py, tests/core/project_handler_test.py, tests/usage_test.py
I have had some trouble with imports due to my project setup.
By adding 2 new flags, we can alter how pyt expects a project to be setup. I hope you don't think it makes things too complicated.
For a project with root in /app, currently pyt expects that all of the imports are of the form:
`from app.folder.module import thing`
But actually a project could not be expecting the module root to be prepended.
My projects use:
`from folder.module import thing`
I also had a problem where one of my directories had a file called flask.py.
Because of this, any imports of the package flask were causing pyt to import from the local file flask.py. In my project this caused a circular import and RecursionError which crashed pyt.
My projects always either use relative imports with `from .somewhere.else …
=> Import woes

.travis.yml, pyt/usage.py, requirements-dev.txt, requirements.txt, setup.py, tox.ini
Requirements:
Requirements files aren't used. Requirements.txt and setup.py had odd
requirements that I can't see used anywhere. Requirements-dev.txt had
conflicting packages (flake8 wants specific versions of pyflakes and
pycodestyle).
Tox & travis:
Split tox into a test, coverage and lint phase. Run either:
```
tox  # Run all
tox -e py36
tox -e cover
tox -e lint
```
Tox and travis will now fail the lint / build on flake8 errors to
avoid non-compliant code being merged. (`--exit-zero` removed)
Coverage will fail for now, so let's not put it in the travis build yet.
McCabe complexity is annoying and dealt with better by codeclimate so I
bumped it up from 10 to 11 so it won't fail at the moment.
=> Tox, travis and requirements

pyt/__main__.py, setup.py, tests/main_test.py
Not sure if you want this, but having a non-zero exit code if there are vulnerabilities would help with using pyt in an automated system like CI.
=> Exit code 1 if unsanitised vulnerabilities found

examples/example_inputs/generator_with_multiple_yields.py, examples/vulnerable_code/yield.py, pyt/cfg/expr_visitor.py, pyt/cfg/stmt_visitor.py, pyt/core/README.rst, pyt/core/node_types.py, pyt/vulnerabilities/vulnerability_helper.py, tests/cfg/cfg_test.py, tests/main_test.py, tests/vulnerabilities/vulnerabilities_test.py
Previously `+=` only propagated taint of the last assigment. Now, the original variable is added to `right_hand_side_variables`.
Yield and YieldFrom are treated a bit like augmented assignment, giving the function a final return variable `yld_` a bit like `ret_`. Really it's a generator function, but we can treat it as a normal function. So anything yielded propagates taint to the overall "return" value of the function.
=> Yield, YieldFrom, AugAssign propagate taint

examples/example_inputs/asynchronous.py, pyt/core/ast_helper.py, pyt/core/transformer.py, pyt/helper_visitors/vars_visitor.py, tests/cfg/cfg_test.py, tests/core/transformer_test.py
Transform all async ast nodes into sync nodes  …
so that they can be handled identically. Sync and async nodes propagate
taint in exactly the same way.
Awaits are more or less removed:
`return await x()` is converted into `return x()`.
Any AsyncFunctionDef is converted to a FunctionDef.
Same for AsyncFor and AsyncWith.
Using a transformer makes it easier to replace awaits everywhere (c.f. a different attempt at https://github.com/bcaller/pyt/commits/await ).
We have lots of places where we do `isinstance(node, ast.Call)` but for these we want it to function like `isinstance(node, ast.Call) or (isinstance(node, ast.Await) and isinstance(node.value, ast.Call))`
=> Transform all async ast nodes into sync nodes

tests/main_test.py, tox.ini
https://docs.python.org/3/library/unittest.mock.html
"Pyt runs on python 3.6+":
https://github.com/python-security/pyt/commit/609acd6ca7e3800f21e82d5e3736e8112a91b49c#r29924039
=> mock is included in unittest since Python 3.3

pyt/cfg/stmt_visitor.py, tests/cfg/cfg_test.py
We already handle
`a, b, c = d, *e, f`
`a, b, c = d()`
But `a, b, c = d` prints 'Assignment not properly handled.'
This can be handled exactly like `a, b, c = (*d,)`, where taint in
value `d` is propagated to all targets.
=> Handle assignment unpacking a, b, c = d

pyt/cfg/stmt_visitor.py, pyt/helper_visitors/vars_visitor.py, tests/helper_visitors/vars_visitor_test.py
Fixed so that it doesn't crash and so the result will be `[ret_g, b, c]` as per @KevinHock's suggestion. The solution I've done is a bit ugly so feel free to suggest changes.
First commit fixes a small bug with keyword arguments not being treated correctly.
Fixes #157
=> Fix VarsVisitor RuntimeError on code like f(g(a)(b)(c))

pyt/__main__.py
`os.walk` is not deterministic (though often on the same computer it will
walk in the same order).
This means that the vulnerabilities can appear in different orders, making it hard to compare output.
Process files in alphabetical order.
I do need to look more deeply into how the import system works because I think there are some other non-determinism problems which can result in vulnerabilities not being found but I haven't figured it out yet.
=> Deterministic file loading and vulnerability order

pyt/vulnerabilities/vulnerability_helper.py, tests/vulnerabilities/vulnerabilities_test.py
The output should consist of the path from the source to the sink.
Anything which happens after the source reaches the sink is irrelevant
and just makes the output longer and confusing to interpret.
None of the lines removed from the tests actually affected the
vulnerability chain.
Perhaps this should be dealt with somewhere in the definition_chain or
vulnerability functions: here we just trim the chain upon reaching the
sink in the vulnerability_helper.
=> Remove extraneous reassignments in output

pyt/cfg/stmt_visitor.py, tests/vulnerabilities/vulnerabilities_test.py
Previously
`x = TAINT.lower()` would be tainted (due to special handling for assignment_call_nodes)
but
`x = str(TAINT.lower())` wouldn't be tainted.
To fix this, `TAINT` is added to the RHS variables of
`TAINT.lower()`.
This will mean that e.g. `request` will be a RHS variable of
`request.get()`, but I think that will be OK.
In the test which changed, the additional line is because resp has
become tainted.
However, this still leaves the following false negatives to fix another
day:
`assert_vulnerable('result = str("%s" % str(TAINT.lower()))')  # FAILS`
`assert_vulnerable('result = str("%s" % TAINT.lower().upper())') # FAILS`
=> Taint propagates from methods of tainted objects

pyt/core/ast_helper.py, pyt/core/transformer.py, tests/base_test_case.py, tests/cfg/cfg_test.py, tests/core/transformer_test.py, tests/vulnerabilities/vulnerabilities_test.py
Take the example from examples/vulnerable_code/sql/sqli.py:
```python
result = session.query(User).filter("username={}".format(TAINT))
```
The `filter` function is marked as a sink. However, previously this did not get marked as a vulnerability. The call label used to be `session.query`, ignoring the filter function.
Now, when the file is read, it is transformed into 2 lines:
```python
__chain_tmp_1 = session.query(User)
result = __chain_tmp_1.filter("username={}".format(TAINT))
```
before converting to a CFG. The vulnerability is now found.
We don't find everything here: just ordinary assignments and return statements. We can't just transform all Call nodes here since Call nodes can appear in many different scenarios e.g. comprehensions, bare function calls. Because of this, it may be …
=> Chained function calls separated into multiple assignments

examples/vulnerable_code/recursive.py, pyt/__main__.py, pyt/cfg/expr_visitor.py, pyt/web_frameworks/framework_adaptor.py, tests/cfg/cfg_test.py, tests/main_test.py, tests/vulnerabilities/vulnerabilities_test.py
Store a stack of definitions.
If you revisit a function, treat it as a blackbox.
The non-recursive return values should still propagate.
=>  Recursive function calls shouldn't raise RecursionError

examples/example_inputs/ternary.py, pyt/core/transformer.py, pyt/helper_visitors/label_visitor.py, pyt/helper_visitors/right_hand_side_visitor.py, tests/cfg/cfg_test.py, tests/core/transformer_test.py, tests/helper_visitors/label_visitor_test.py
Reduces false positives.
As an example:
`result = "a" if TAINT else "c"`
In AST, the assignment value is `IfExp(test=TAINT, body="a", orelse="c")`.
Even though `TAINT` is inside the assignment of `result`, it can't
actually taint `result` as it is part of the boolean test expression.
Previously, `result` would have been tainted, which was a false
positive.
We don't want to completely ignore the test though in case it contains a
sink function.
Therefore, if the test contains expressions we transform it as so:
`result = "a" if b(c) + 2 else "d"`
to the multi line:
```python
__if_exp_0 = b(c) + 2
result = "a" if __if_exp_0 else "d"
```
This way if `b` is a sink and `c` is tainted we see a vulnerability, but
even if `c` is tainted we don't taint `result`.
=> Better handling of IfExp (ternary)

examples/vulnerable_code/list_append.py, pyt/cfg/expr_visitor.py, pyt/cfg/expr_visitor_helper.py, tests/main_test.py, tests/vulnerabilities/vulnerabilities_test.py
Taint is propagated by:
```
list += [TAINT]
list = list + TAINT
```
but with lists we often use a function to mutate the list:
```
list = []
list.append(TAINT)
list.insert(0, TAINT)
list.extend(TAINT)
```
Previously this didn't taint `list` so we had FALSE NEGATIVES.
Now `list.append(TAINT)` is treated like augmented assignment, so list
will be tainted.
`list += list.append(TAINT)`
Of course this wouldn't work as real code since `append` returns `None`
but it is how you can think about this function which mutates `list`.
The same goes for `set.add()`, `list.extend()`, `list.insert()`,
`dict.update()`, although we aren't actually doing type checking, just
looking at the name of the method.
=> list is tainted by calling list.append(TAINT)

pyt/vulnerabilities/trigger_definitions_parser.py, pyt/vulnerabilities/vulnerabilities.py, pyt/vulnerability_definitions/test_positions.pyt, tests/vulnerabilities/vulnerabilities_test.py
This changes the schema of the trigger file.
Previously there were too many options and it was confusing. My fault,
sorry.
This meant that `db.execute(query, **TAINT)` was marked as a
vulnerability whereas `db.execute(text=query, **TAINT)` wasn't.
Neither are vulnerabilities, so this gave a FALSE POSITIVE.
Now we have `arg_dict` which is a dictionary of keyword to argument
position.
E.g. for `def f(a, b, *, c)` we can specify the arg_dict as:
```
{"a": 0, "b": 1, "c": null}
```
if we want them all to propagate or not propagate depending on the
`unlisted_args_propagate` value.
This way, we can more easily define db.execute as:
```
"execute(": {
"unlisted_args_propagate": false,
"arg_dict": {
"text": 0
}
},
```
=> Simplify trigger file for sink argument propagation

CHANGELOG.md, MANIFEST.in, setup.py
No actual code changes here.
I accidentally uploaded some vim undo files inside the package added to
pypi for 0.41.
=> [version] Bump 0.42

examples/example_inputs/while_func_comparator.py, examples/example_inputs/while_func_comparator_lhs.py, examples/example_inputs/while_func_comparator_rhs.py, pyt/cfg/stmt_visitor.py, tests/cfg/cfg_test.py
Hi!
I've tried to resolve #133 with this PR. I hope I understood what the issue described, but this is my first foray into pyt (and contributions to static analysis tools) so take it with a grain of salt. In particular I'm not 100% convinced about the generated CFG and I'd appreciate a keen eye on the unit test's node relationships.
Let me know if you want me to make changes or if I completely missed the mark!
Regards,
Adrian
=> 133: Visit functions in while test

pyt/vulnerabilities/vulnerabilities.py
Flake8 Tavis Failure: `continuation line under-indented for visual indent`
=> :bug: Fix E128

pyt/vulnerabilities/vulnerabilities.py
This should resolve #128. The change is so straight forward and any potential tests would be awkward, so I'm not sure we want to include specific tests for this (there were none before for interactive mode anyway). 
I'm open to suggestions though. 
You can manually test this change by using this sample code:
```python
import scrypt
image_name = request.args.get('image_name')
if not image_name:
image_name = 'foo'
foo = scrypt.outer(image_name) # Any call after ControlFlowNode caused the problem
foo = scrypt.hash(foo, 'salt')
foo = scrypt.encrypt(os.urandom(datalength), foo)
send_file(foo)
```
Then `python -m pyt sample.py -m bb.txt -i`. You can see how it does as many as you want until you answer `s`.
=> 128: Allow the user to cancel interactive mode

examples/vulnerable_code/command_injection_with_aliases.py, pyt/cfg/alias_helper.py, pyt/cfg/stmt_visitor.py, pyt/vulnerability_definitions/all_trigger_words.pyt, tests/main_test.py, tests/vulnerabilities/vulnerabilities_across_files_test.py, tests/vulnerabilities/vulnerabilities_base_test_case.py, tests/vulnerabilities/vulnerabilities_test.py
Remember import aliases for built-in and black box functions.
* This allows sinks to be fully qualified
* I.e. we can use `os.system` and it will match even if the import us done using `from os import system`
*This is an incompatible change*. The labels for function calls changed (they are now fully qualified, regardless of how the function was imported).
This solves #177
=> 177 support from import sinks

README.rst
It wasn't clear to me getting started that having python3.6 or 3.7 was essential.  This just adds a line to the readme describing that.
=> Document python version to use

pyt/vulnerability_definitions/all_trigger_words.pyt
In #200 some sinks were added for shell injection.  This adds 'exec' and 'eval', the built-in keywords, to the list.
=> adding eval, exec sinks
